## The coverity binary needs to be downloaded from an authenticated
## account, so this Docker image can't be built automatically in the
## cloud
FROM amarburg/lsdslam-dev-host:nvidia_cuda_nocv

RUN sudo apt-get install --no-install-recommends --yes libopencv-dev
